spring.application.name=MICROSERVICIO-TECNOLOGIA
spring.profiles.active=local
  
  # --- Servidor y Ciclo de Vida ---
server.port=8081
server.shutdown=graceful
spring.lifecycle.timeout-per-shutdown-phase=20s
  
  # --- Base de Datos R2DBC (MySQL) ---
spring.r2dbc.url=r2dbc:mysql://localhost:3306/tecnologia_db?serverTimezone=America/Bogota
spring.r2dbc.username=user_tecno
spring.r2dbc.password=18566621
spring.r2dbc.pool.enabled=true
spring.r2dbc.pool.initial-size=5
spring.r2dbc.pool.max-size=20
spring.r2dbc.pool.max-idle-time=30m
spring.r2dbc.pool.validation-query=SELECT 1
spring.sql.init.mode=always
  
  # --- Swagger / OpenAPI ---
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.api-docs.path=/v3/api-docs
  
  # =========================================================
  # RESILIENCE4J - CONFIGURACI�N
  # =========================================================
resilience4j.circuitbreaker.circuit-breaker-aspect-order=1
  
  # --- Configuraci�n Base 'default' ---
resilience4j.circuitbreaker.configs.default.register-health-indicator=true
resilience4j.circuitbreaker.configs.default.sliding-window-type=COUNT_BASED
resilience4j.circuitbreaker.configs.default.sliding-window-size=10
resilience4j.circuitbreaker.configs.default.minimum-number-of-calls=5
resilience4j.circuitbreaker.configs.default.failure-rate-threshold=50
resilience4j.circuitbreaker.configs.default.slow-call-rate-threshold=50
resilience4j.circuitbreaker.configs.default.slow-call-duration-threshold=2s
resilience4j.circuitbreaker.configs.default.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.configs.default.max-wait-duration-in-half-open-state=5s
resilience4j.circuitbreaker.configs.default.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.configs.default.automatic-transition-from-open-to-half-open-enabled=false
  
  # --- Instancias ---
resilience4j.circuitbreaker.instances.tecnologia-db.base-config=default
resilience4j.circuitbreaker.instances.tecnologia-db.record-exceptions=org.springframework.dao.DataAccessException

resilience4j.circuitbreaker.instances.capacidad-db.base-config=default
resilience4j.circuitbreaker.instances.capacidad-db.record-exceptions=org.springframework.dao.DataAccessException

resilience4j.circuitbreaker.instances.bootcamp-db.base-config=default
resilience4j.circuitbreaker.instances.bootcamp-db.record-exceptions=org.springframework.dao.DataAccessException
  
  # --- Time Limiter ---
resilience4j.timelimiter.instances.tecnologia-db.timeout-duration=3s
resilience4j.timelimiter.instances.capacidad-db.timeout-duration=3s
resilience4j.timelimiter.instances.bootcamp-db.timeout-duration=3s
  
  # --- Actuator ---
management.health.circuitbreakers.enabled=true