spring:
  config:
    activate:
      on-profile: local  # Mantiene el perfil 'local'
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver  # Asegurar que el nombre de la propiedad es correcto
    url: jdbc:mysql://localhost:3306/''?serverTimezone=America/Bogota  # URL de conexión
    username: root
    password:
  jpa:
    properties:
      hibernate:
        jdbc:
          time_zone: America/Bogota
    hibernate:
      ddl-auto: update  # O 'none' si no quieres que Hibernate modifique la BD
    database-platform: org.hibernate.dialect.MySQL8Dialect
